// <auto-generated />
// Hand-maintained strongly-typed resource accessor.
// Regenerate if new keys are added to AppResources.resx.
#nullable enable

using System.Globalization;
using System.Resources;

namespace NolumiaScheduler.Presentation.Resources.Strings;

public static class AppResources
{
    private static ResourceManager? _resourceMan;

    public static ResourceManager ResourceManager
    {
        get
        {
            _resourceMan ??= new ResourceManager(
                "NolumiaScheduler.Presentation.Resources.Strings.AppResources",
                typeof(AppResources).Assembly);
            return _resourceMan;
        }
    }

    /// <summary>Overrides the culture used for all lookups. Null = thread UI culture.</summary>
    public static CultureInfo? Culture { get; set; }

    /// <summary>Culture used for locale-sensitive date formatting.</summary>
    public static CultureInfo FormatCulture =>
        Culture ?? CultureInfo.CurrentUICulture;

    public static string CalendarTitle => Get(nameof(CalendarTitle));
    public static string TodayButton   => Get(nameof(TodayButton));

    public static string DaySun => Get(nameof(DaySun));
    public static string DayMon => Get(nameof(DayMon));
    public static string DayTue => Get(nameof(DayTue));
    public static string DayWed => Get(nameof(DayWed));
    public static string DayThu => Get(nameof(DayThu));
    public static string DayFri => Get(nameof(DayFri));
    public static string DaySat => Get(nameof(DaySat));

    public static string MonthViewLabel    => Get(nameof(MonthViewLabel));
    public static string WeekViewLabel     => Get(nameof(WeekViewLabel));
    public static string WeekdaysViewLabel => Get(nameof(WeekdaysViewLabel));
    public static string WeekViewHint      => Get(nameof(WeekViewHint));

    public static string AllDay         => Get(nameof(AllDay));
    public static string NoEventsLabel  => Get(nameof(NoEventsLabel));
    public static string BadgeMoved     => Get(nameof(BadgeMoved));
    public static string BadgeModified  => Get(nameof(BadgeModified));

    public static string MonthYearFormat   => Get(nameof(MonthYearFormat));
    public static string SelectedDayFormat => Get(nameof(SelectedDayFormat));
    public static string HolidayDateFormat => Get(nameof(HolidayDateFormat));

    // Event colors
    public static string ColorLabel     => Get(nameof(ColorLabel));
    public static string ColorDefault   => Get(nameof(ColorDefault));
    public static string ColorTomato    => Get(nameof(ColorTomato));
    public static string ColorTangerine => Get(nameof(ColorTangerine));
    public static string ColorBanana    => Get(nameof(ColorBanana));
    public static string ColorBasil     => Get(nameof(ColorBasil));
    public static string ColorSage      => Get(nameof(ColorSage));
    public static string ColorPeacock   => Get(nameof(ColorPeacock));
    public static string ColorBlueberry => Get(nameof(ColorBlueberry));
    public static string ColorLavender  => Get(nameof(ColorLavender));
    public static string ColorGrape     => Get(nameof(ColorGrape));
    public static string ColorGraphite  => Get(nameof(ColorGraphite));

    // Tabs
    public static string CalendarTab          => Get(nameof(CalendarTab));
    public static string BusinessCalendarsTab => Get(nameof(BusinessCalendarsTab));

    // Business Calendar List
    public static string NoCalendarsLabel  => Get(nameof(NoCalendarsLabel));
    public static string AddCalendarButton => Get(nameof(AddCalendarButton));

    // Business Calendar Edit
    public static string NewCalendarTitle        => Get(nameof(NewCalendarTitle));
    public static string EditCalendarTitle       => Get(nameof(EditCalendarTitle));
    public static string CalendarNamePlaceholder => Get(nameof(CalendarNamePlaceholder));
    public static string WorkdaysLabel           => Get(nameof(WorkdaysLabel));
    public static string HolidaysLabel           => Get(nameof(HolidaysLabel));
    public static string AddHolidayButton        => Get(nameof(AddHolidayButton));
    public static string HolidayNamePlaceholder  => Get(nameof(HolidayNamePlaceholder));
    public static string SaveButton              => Get(nameof(SaveButton));
    public static string DeleteCalendarButton    => Get(nameof(DeleteCalendarButton));

    // Event Edit
    public static string NewEventTitle            => Get(nameof(NewEventTitle));
    public static string EventTitlePlaceholder    => Get(nameof(EventTitlePlaceholder));
    public static string EventLocationPlaceholder => Get(nameof(EventLocationPlaceholder));
    public static string StartLabel               => Get(nameof(StartLabel));
    public static string EndLabel                 => Get(nameof(EndLabel));
    public static string RepeatLabel              => Get(nameof(RepeatLabel));
    public static string RepeatNone               => Get(nameof(RepeatNone));
    public static string RepeatWeekly             => Get(nameof(RepeatWeekly));
    public static string RepeatMonthly            => Get(nameof(RepeatMonthly));
    public static string RepeatYearly             => Get(nameof(RepeatYearly));
    public static string WeekdaysLabel            => Get(nameof(WeekdaysLabel));
    public static string MonthlyDayOfMonth        => Get(nameof(MonthlyDayOfMonth));
    public static string MonthlyNthWeekday        => Get(nameof(MonthlyNthWeekday));
    public static string DayLabel                 => Get(nameof(DayLabel));
    public static string MonthLabel               => Get(nameof(MonthLabel));
    public static string WeekIndexLabel           => Get(nameof(WeekIndexLabel));
    public static string NthWeekLast              => Get(nameof(NthWeekLast));
    public static string IntervalLabel            => Get(nameof(IntervalLabel));
    public static string EndDateLabel             => Get(nameof(EndDateLabel));
    public static string AdjustmentLabel          => Get(nameof(AdjustmentLabel));
    public static string AdjustmentNone           => Get(nameof(AdjustmentNone));
    public static string AdjustmentForward        => Get(nameof(AdjustmentForward));
    public static string AdjustmentBackward       => Get(nameof(AdjustmentBackward));
    public static string BusinessCalendarLabel    => Get(nameof(BusinessCalendarLabel));
    public static string ErrorTitleRequired       => Get(nameof(ErrorTitleRequired));
    public static string ErrorWeekdayRequired     => Get(nameof(ErrorWeekdayRequired));
    public static string ErrorEndDateBeforeStart  => Get(nameof(ErrorEndDateBeforeStart));

    // Event actions
    public static string EditButton              => Get(nameof(EditButton));
    public static string DeleteButton            => Get(nameof(DeleteButton));
    public static string CancelButton            => Get(nameof(CancelButton));
    public static string ReplaceButton           => Get(nameof(ReplaceButton));
    public static string ReplaceHolidayMessage   => Get(nameof(ReplaceHolidayMessage));
    public static string DeleteEventTitle        => Get(nameof(DeleteEventTitle));
    public static string DeleteOccurrence        => Get(nameof(DeleteOccurrence));
    public static string DeleteAllOccurrences    => Get(nameof(DeleteAllOccurrences));
    public static string EditEventTitle          => Get(nameof(EditEventTitle));

    // Recurring edit
    public static string EditRecurringEventTitle          => Get(nameof(EditRecurringEventTitle));
    public static string EditThisOccurrence               => Get(nameof(EditThisOccurrence));
    public static string EditThisAndFollowing             => Get(nameof(EditThisAndFollowing));
    public static string EditEntireSeries                 => Get(nameof(EditEntireSeries));
    public static string EditRecurringScopeRequired       => Get(nameof(EditRecurringScopeRequired));
    public static string EditThisOccurrenceNotImplemented => Get(nameof(EditThisOccurrenceNotImplemented));
    public static string EditThisAndFollowingNotImplemented => Get(nameof(EditThisAndFollowingNotImplemented));

    // Alarm
    public static string AlarmLabel          => Get(nameof(AlarmLabel));
    public static string AlarmEnable         => Get(nameof(AlarmEnable));
    public static string AlarmNotify15Min    => Get(nameof(AlarmNotify15Min));
    public static string AlarmNotify5Min     => Get(nameof(AlarmNotify5Min));
    public static string AlarmNotify1Min     => Get(nameof(AlarmNotify1Min));
    public static string AlarmNotifyAtStart  => Get(nameof(AlarmNotifyAtStart));
    public static string AlarmDismiss        => Get(nameof(AlarmDismiss));
    public static string AlarmSnooze5Min     => Get(nameof(AlarmSnooze5Min));
    public static string AlarmSnooze1Min     => Get(nameof(AlarmSnooze1Min));
    public static string AlarmSnoozeReminder => Get(nameof(AlarmSnoozeReminder));
    public static string AlarmNotify15MinMsg => Get(nameof(AlarmNotify15MinMsg));
    public static string AlarmNotify5MinMsg  => Get(nameof(AlarmNotify5MinMsg));
    public static string AlarmNotify1MinMsg  => Get(nameof(AlarmNotify1MinMsg));
    public static string AlarmNotify0MinMsg  => Get(nameof(AlarmNotify0MinMsg));
    public static string AlarmWindowTitle     => Get(nameof(AlarmWindowTitle));
    public static string AlarmOpenLocation    => Get(nameof(AlarmOpenLocation));
    public static string AlarmSnoozeTo5MinBefore => Get(nameof(AlarmSnoozeTo5MinBefore));
    public static string AlarmSnoozeTo1MinBefore => Get(nameof(AlarmSnoozeTo1MinBefore));
    public static string AlarmCancelAll       => Get(nameof(AlarmCancelAll));
    public static string AlarmSnooze5MinBtn   => Get(nameof(AlarmSnooze5MinBtn));
    public static string AlarmSnooze1MinBtn   => Get(nameof(AlarmSnooze1MinBtn));
    public static string AlarmNextAlarmFormat => Get(nameof(AlarmNextAlarmFormat));
    public static string AlarmOffsetsHeader   => Get(nameof(AlarmOffsetsHeader));
    public static string AlarmSetNextHeader   => Get(nameof(AlarmSetNextHeader));
    public static string AlarmSetFromNowLabel => Get(nameof(AlarmSetFromNowLabel));
    public static string AlarmSetBeforeStartLabel => Get(nameof(AlarmSetBeforeStartLabel));
    public static string AlarmSetButton       => Get(nameof(AlarmSetButton));

    // Settings
    public static string SettingsTitle   => Get(nameof(SettingsTitle));
    public static string ThemeLabel      => Get(nameof(ThemeLabel));
    public static string ThemeSystem     => Get(nameof(ThemeSystem));
    public static string ThemeLight      => Get(nameof(ThemeLight));
    public static string ThemeDark       => Get(nameof(ThemeDark));
    public static string LanguageLabel   => Get(nameof(LanguageLabel));
    public static string StartupViewLabel => Get(nameof(StartupViewLabel));
    public static string LanguageEnglish => Get(nameof(LanguageEnglish));
    public static string LanguageJapanese => Get(nameof(LanguageJapanese));
    public static string SettingsVersionLabel => Get(nameof(SettingsVersionLabel));
    public static string SettingsStorageLabel => Get(nameof(SettingsStorageLabel));
    public static string SettingsOpenDataFolderLink => Get(nameof(SettingsOpenDataFolderLink));

    private static string Get(string name) =>
        ResourceManager.GetString(name, Culture) ?? name;
}
