// <auto-generated />
// Hand-maintained strongly-typed resource accessor.
// Regenerate if new keys are added to AppResources.resx.

using System.Globalization;
using System.Resources;

namespace NolumiaScheduler.Resources.Strings;

public static class AppResources
{
    private static ResourceManager? _resourceMan;

    public static ResourceManager ResourceManager
    {
        get
        {
            _resourceMan ??= new ResourceManager(
                "NolumiaScheduler.Resources.Strings.AppResources",
                typeof(AppResources).Assembly);
            return _resourceMan;
        }
    }

    /// <summary>Overrides the culture used for all lookups. Null = thread UI culture.</summary>
    public static CultureInfo? Culture { get; set; }

    /// <summary>Culture used for locale-sensitive date formatting.</summary>
    public static CultureInfo FormatCulture =>
        Culture ?? CultureInfo.CurrentUICulture;

    public static string CalendarTitle => Get(nameof(CalendarTitle));
    public static string TodayButton   => Get(nameof(TodayButton));

    public static string DaySun => Get(nameof(DaySun));
    public static string DayMon => Get(nameof(DayMon));
    public static string DayTue => Get(nameof(DayTue));
    public static string DayWed => Get(nameof(DayWed));
    public static string DayThu => Get(nameof(DayThu));
    public static string DayFri => Get(nameof(DayFri));
    public static string DaySat => Get(nameof(DaySat));

    public static string AllDay         => Get(nameof(AllDay));
    public static string NoEventsLabel  => Get(nameof(NoEventsLabel));
    public static string BadgeMoved     => Get(nameof(BadgeMoved));
    public static string BadgeModified  => Get(nameof(BadgeModified));

    public static string MonthYearFormat   => Get(nameof(MonthYearFormat));
    public static string SelectedDayFormat => Get(nameof(SelectedDayFormat));

    // Tabs
    public static string CalendarTab        => Get(nameof(CalendarTab));
    public static string BusinessCalendarsTab => Get(nameof(BusinessCalendarsTab));

    // Business Calendar List
    public static string NoCalendarsLabel  => Get(nameof(NoCalendarsLabel));
    public static string AddCalendarButton => Get(nameof(AddCalendarButton));

    // Business Calendar Edit
    public static string NewCalendarTitle      => Get(nameof(NewCalendarTitle));
    public static string EditCalendarTitle     => Get(nameof(EditCalendarTitle));
    public static string CalendarNamePlaceholder => Get(nameof(CalendarNamePlaceholder));
    public static string WorkdaysLabel         => Get(nameof(WorkdaysLabel));
    public static string HolidaysLabel         => Get(nameof(HolidaysLabel));
    public static string AddHolidayButton      => Get(nameof(AddHolidayButton));
    public static string HolidayNamePlaceholder => Get(nameof(HolidayNamePlaceholder));
    public static string SaveButton            => Get(nameof(SaveButton));
    public static string DeleteCalendarButton  => Get(nameof(DeleteCalendarButton));

    // Event Edit
    public static string NewEventTitle          => Get(nameof(NewEventTitle));
    public static string EventTitlePlaceholder  => Get(nameof(EventTitlePlaceholder));
    public static string EventLocationPlaceholder => Get(nameof(EventLocationPlaceholder));
    public static string StartLabel             => Get(nameof(StartLabel));
    public static string EndLabel               => Get(nameof(EndLabel));
    public static string RepeatLabel            => Get(nameof(RepeatLabel));
    public static string RepeatNone             => Get(nameof(RepeatNone));
    public static string RepeatWeekly           => Get(nameof(RepeatWeekly));
    public static string RepeatMonthly          => Get(nameof(RepeatMonthly));
    public static string RepeatYearly           => Get(nameof(RepeatYearly));
    public static string WeekdaysLabel          => Get(nameof(WeekdaysLabel));
    public static string MonthlyDayOfMonth      => Get(nameof(MonthlyDayOfMonth));
    public static string MonthlyNthWeekday      => Get(nameof(MonthlyNthWeekday));
    public static string DayLabel               => Get(nameof(DayLabel));
    public static string MonthLabel             => Get(nameof(MonthLabel));
    public static string WeekIndexLabel         => Get(nameof(WeekIndexLabel));
    public static string NthWeekLast            => Get(nameof(NthWeekLast));
    public static string IntervalLabel          => Get(nameof(IntervalLabel));
    public static string EndDateLabel           => Get(nameof(EndDateLabel));
    public static string AdjustmentLabel        => Get(nameof(AdjustmentLabel));
    public static string AdjustmentNone         => Get(nameof(AdjustmentNone));
    public static string AdjustmentForward      => Get(nameof(AdjustmentForward));
    public static string AdjustmentBackward     => Get(nameof(AdjustmentBackward));
    public static string BusinessCalendarLabel  => Get(nameof(BusinessCalendarLabel));
    public static string ErrorTitleRequired     => Get(nameof(ErrorTitleRequired));
    public static string ErrorWeekdayRequired   => Get(nameof(ErrorWeekdayRequired));

    // Event actions
    public static string EditButton              => Get(nameof(EditButton));
    public static string DeleteButton            => Get(nameof(DeleteButton));
    public static string CancelButton            => Get(nameof(CancelButton));
    public static string DeleteEventTitle        => Get(nameof(DeleteEventTitle));
    public static string DeleteOccurrence        => Get(nameof(DeleteOccurrence));
    public static string DeleteAllOccurrences    => Get(nameof(DeleteAllOccurrences));
    public static string EditEventTitle          => Get(nameof(EditEventTitle));

    private static string Get(string name) =>
        ResourceManager.GetString(name, Culture) ?? name;
}
