// <auto-generated />
// Hand-maintained strongly-typed resource accessor.
// Regenerate if new keys are added to AppResources.resx.

using System.Globalization;
using System.Resources;

namespace NolumiaScheduler.Resources.Strings;

public static class AppResources
{
    private static ResourceManager? _resourceMan;

    public static ResourceManager ResourceManager
    {
        get
        {
            _resourceMan ??= new ResourceManager(
                "NolumiaScheduler.Resources.Strings.AppResources",
                typeof(AppResources).Assembly);
            return _resourceMan;
        }
    }

    /// <summary>Overrides the culture used for all lookups. Null = thread UI culture.</summary>
    public static CultureInfo? Culture { get; set; }

    /// <summary>Culture used for locale-sensitive date formatting.</summary>
    public static CultureInfo FormatCulture =>
        Culture ?? CultureInfo.CurrentUICulture;

    public static string CalendarTitle => Get(nameof(CalendarTitle));
    public static string TodayButton   => Get(nameof(TodayButton));

    public static string DaySun => Get(nameof(DaySun));
    public static string DayMon => Get(nameof(DayMon));
    public static string DayTue => Get(nameof(DayTue));
    public static string DayWed => Get(nameof(DayWed));
    public static string DayThu => Get(nameof(DayThu));
    public static string DayFri => Get(nameof(DayFri));
    public static string DaySat => Get(nameof(DaySat));

    public static string AllDay         => Get(nameof(AllDay));
    public static string NoEventsLabel  => Get(nameof(NoEventsLabel));
    public static string BadgeMoved    => Get(nameof(BadgeMoved));
    public static string BadgeModified => Get(nameof(BadgeModified));

    public static string MonthYearFormat   => Get(nameof(MonthYearFormat));
    public static string SelectedDayFormat => Get(nameof(SelectedDayFormat));

    private static string Get(string name) =>
        ResourceManager.GetString(name, Culture) ?? name;
}
